import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export async function GET(req: NextRequest) {
  const apiKey = req.headers.get("x-api-key");
  const isUiPath = apiKey === process.env.UIPATH_API_KEY;

  if (!isUiPath) {
    const session = await getServerSession(authOptions);
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const since = searchParams.get("since")
    ? new Date(searchParams.get("since")!)
    : new Date(Date.now() - 24 * 60 * 60 * 1000);

  const [
    totalCreated,
    totalUpdated,
    totalDuplicates,
    totalFailed,
    recentArticles,
    failedInputs,
  ] = await Promise.all([
    prisma.rawInput.count({ where: { status: "done", createdAt: { gte: since } } }),
    prisma.articleVersion.count({ where: { action: "edited", createdAt: { gte: since } } }),
    prisma.rawInput.count({ where: { status: "duplicate", createdAt: { gte: since } } }),
    prisma.rawInput.count({ where: { status: "failed", createdAt: { gte: since } } }),
    prisma.article.findMany({
      where: { createdAt: { gte: since } },
      select: { id: true, title: true, status: true, sourceType: true, createdAt: true },
      orderBy: { createdAt: "desc" },
    }),
    prisma.rawInput.findMany({
      where: { status: "failed", updatedAt: { gte: since } },
      select: { id: true, type: true, errorMsg: true, updatedAt: true, source: true },
    }),
  ]);

  const report = {
    period: { from: since.toISOString(), to: new Date().toISOString() },
    summary: {
      created: totalCreated,
      updated: totalUpdated,
      duplicates: totalDuplicates,
      failed: totalFailed,
    },
    articles: recentArticles,
    errors: failedInputs,
    generatedAt: new Date().toISOString(),
  };

  return NextResponse.json(report);
}

// UiPath calls this to trigger sending the summary email
export async function POST(req: NextRequest) {
  const apiKey = req.headers.get("x-api-key");
  const isUiPath = apiKey === process.env.UIPATH_API_KEY;

  if (!isUiPath) {
    const session = await getServerSession(authOptions);
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json().catch(() => ({}));
  const adminEmail = body.adminEmail ?? process.env.ADMIN_EMAIL ?? "admin@dhl.com";
  const since = body.since ? new Date(body.since) : new Date(Date.now() - 24 * 60 * 60 * 1000);

  // Get stats
  const [created, updated, duplicates, failed] = await Promise.all([
    prisma.rawInput.count({ where: { status: "done", createdAt: { gte: since } } }),
    prisma.articleVersion.count({ where: { action: "edited", createdAt: { gte: since } } }),
    prisma.rawInput.count({ where: { status: "duplicate", createdAt: { gte: since } } }),
    prisma.rawInput.count({ where: { status: "failed", createdAt: { gte: since } } }),
  ]);

  const failedDetails = await prisma.rawInput.findMany({
    where: { status: "failed", updatedAt: { gte: since } },
    select: { id: true, type: true, errorMsg: true },
  });

  // Send email if SMTP configured
  if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
    const nodemailer = await import("nodemailer");
    const transporter = nodemailer.default.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT ?? "587"),
      secure: false,
      auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
    });

    const errorLines = failedDetails.map(
      (f) => `  - [${f.type.toUpperCase()}] ID: ${f.id} — ${f.errorMsg ?? "Unknown error"}`
    ).join("\n");

    await transporter.sendMail({
      from: process.env.SMTP_USER,
      to: adminEmail,
      subject: `DHL KB System — Daily RPA Summary Report`,
      text: `DHL Knowledge Base — Automation Summary
======================================
Period: ${since.toLocaleDateString()} to ${new Date().toLocaleDateString()}

RESULTS:
  ✅ Articles Created : ${created}
  ✏️  Articles Updated : ${updated}
  ⏭️  Duplicates Skipped: ${duplicates}
  ❌ Failed           : ${failed}

${failed > 0 ? `ERRORS:\n${errorLines}` : "No errors reported."}

Generated by UiPath RPA Bot — DHL DAC 3.0
`,
    });
  }

  return NextResponse.json({
    sent: !!(process.env.SMTP_HOST),
    to: adminEmail,
    summary: { created, updated, duplicates, failed },
  });
}
